;;;; Author: Bahman Movaqar<Bahman@BahmanM.com>
;;;;
(asdf:defsystem "euler-tests"
  :author "Bahman Movaqar <Bahman@BahmanM.com>"
  :license "Apache License v2.0"
  :depends-on ("euler" "fiveam")
  :serial t
  :components ((:module "tests"
                :components ((:file "test-utils")
                             (:file "test-p01")
                             (:file "test-p02")
                             (:file "test-p03")
                             (:file "test-p04")
                             (:file "test-p05")
                             (:file "test-p06")
                             (:file "test-p07")
                             (:file "test-p08")
                             (:file "test-p09")
                             (:file "test-p10")
                             (:file "test-p11")
                             (:file "test-p12")
                             (:file "test-p13")
                             (:file "test-p14")
                             (:file "test-p15")
                             (:file "test-p16")
                             (:file "test-p17")
                             (:file "test-p18")
                             (:file "test-p19")
                             (:file "test-p20")
                             (:file "test-p21")
                             (:file "test-p22")
                             (:file "test-p23")
                             (:file "test-p25")
                             (:file "test-p26")
                             (:file "test-p27")
                             (:file "test-p28")
                             (:file "test-p29")
                             (:file "test-p30")
                             (:file "test-p31")
                             (:file "test-p32")
                             (:file "test-p33")
                             (:file "test-p34")
                             (:file "test-p35")
                             (:file "test-p36")
                             (:file "test-p37"))))
  :perform (asdf:test-op (op system)
                         (let* ((fiveam:*on-failure* :backtrace)
                                (fiveam:*on-error* :backtrace)
                                (fiveam:*verbose-failures* t))
                           (if (fiveam:run-all-tests :summary :end)
                               (format t "✅ All tests passed 😄")
                               (error "❌ At least one suite failed 😓")))))
