---
version: 2.1

jobs:
  test:
    docker:
      - image: bdockerimg/quicklisp.bmakelib:opensuse-tumbleweed
        environment:
          LANG: en_US.UTF-8
    resource_class: medium

    working_directory: ~/euler-cl

    steps:
      - checkout

      - run:
          name: Run the tests
          command: >-
            make test

workflows:
  build_test:
    jobs:
      - test
