---

version: 2.1

jobs:

  test:

    docker:
      - image: opensuse/tumbleweed:latest
        environment:
          LANG: en_US.UTF-8
    resource_class: medium

    working_directory: ~/euler-cl

    steps:

      - run:
          name: Install the runtime
          command: >-
            zypper --non-interactive refresh
            && zypper --non-interactive install sbcl make perl wget
            && rpm --install --nosignature \
                 https://github.com/bahmanm/bmakelib/releases/download/v0.7.0/bmakelib-0.7.0-1.1.noarch.rpm \
            && { source /etc/profile || true; }

      - run:
          name: Install the Lisp packages
          command: >-
            wget -O /tmp/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
            && sbcl
            --load /tmp/quicklisp.lisp
            --eval "(progn
                      (quicklisp-quickstart:install)
                      (ql:quickload :asdf)
                      (asdf:load-system :asdf)
                      (ql:quickload :alexandria)
                      (ql:quickload :fiveam)
                      (ql:quickload :cl-ppcre)
                      (exit))"
            && echo '(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))' > ~/.sbclrc
            && echo '  (when (probe-file quicklisp-init) (load quicklisp-init)))' >> ~/.sbclrc
            && echo '(ql:quickload :alexandria) (ql:quickload :fiveam) (ql:quickload :cl-ppcre)' >> ~/.sbclrc

      - checkout

      - run:
          name: Run the tests
          command: >-
            make test


workflows:
  build_test:
    jobs:
      - test
